title = "Jan Nils Ferner"
description = "The personal webpage of Jan Nils Ferner"
url_prefix = "https://jnferner.com"

[[pages]]
file = "index"

[[pages]]
path = "/about"
file = "about"
Title = "About me"

[[pages]]
file = "_404"
title = "Page Not Found"

[additional]
portrait-url = "https://avatars2.githubusercontent.com/u/9047632"

[assets.style]
source = "sass/style.scss"
